import { useEffect, useState } from 'react'
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Check, ChevronLeft, LoaderCircle, ShieldCheck, Sparkles, X } from 'lucide-react'
import { getProduct, getProducts } from './services/api'
import './App.css'

const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value)
function Header() { return <header className="header"><Link className="logo" to="/products"><span className="logo-mark">1</span>fi<span className="logo-dot">.</span></Link><nav><Link to="/products">Explore phones</Link><span className="secure"><ShieldCheck size={16} /> Secure checkout</span></nav></header> }
function Loading({ label = 'Loading your OneFi experience...' }) { return <div className="state"><LoaderCircle className="spin" size={28} /><p>{label}</p></div> }
function ErrorState({ message }) { return <div className="state error-state"><span>!</span><h2>Something went wrong</h2><p>{message}</p><Link className="button primary" to="/products">Back to catalog</Link></div> }
function ProductImage({ src, alt, className = '' }) { const [failed, setFailed] = useState(false); return failed ? <div className={`image-fallback ${className}`}>1fi</div> : <img className={className} src={src} alt={alt} onError={() => setFailed(true)} /> }

function Catalog() {
  const [products, setProducts] = useState([]); const [status, setStatus] = useState('loading')
  useEffect(() => { getProducts().then(setProducts).then(() => setStatus('ready')).catch(() => setStatus('error')) }, [])
  return <><Header /><main className="catalog"><div className="catalog-intro"><div><p className="eyebrow"><Sparkles size={14} /> SMARTER WAYS TO OWN MORE</p><h1>Choose your next<br /><em>great device.</em></h1></div><p className="intro-copy">Flexible monthly plans backed by your mutual funds. Pick a phone, choose your plan, and keep your savings working.</p></div>{status === 'loading' && <Loading />}{status === 'error' && <ErrorState message="We couldn't reach the product catalog." />}{status === 'ready' && <div className="product-grid">{products.map((product, index) => <Link className="product-card" to={`/products/${product.slug}`} key={product.id}><div className={`product-art art-${index}`}><ProductImage src={product.imageUrl} alt={product.name} /></div><div className="product-card-body"><div><p className="brand">{product.brand}</p><h2>{product.name}</h2><p className="starting">Starting at <strong>{money(product.startingPrice)}</strong></p></div><span className="round-arrow"><ArrowRight size={18} /></span></div></Link>)}</div>}</main><Footer /></>
}

function Detail() {
  const { slug } = useParams(); const navigate = useNavigate(); const [product, setProduct] = useState(null); const [variantIndex, setVariantIndex] = useState(0); const [selectedPlan, setSelectedPlan] = useState(null); const [status, setStatus] = useState('loading'); const [showConfirm, setShowConfirm] = useState(false); const [confirmed, setConfirmed] = useState(false)
  useEffect(() => { getProduct(slug).then((data) => { setProduct(data); setVariantIndex(0); setSelectedPlan(null); setStatus('ready') }).catch(() => setStatus('error')) }, [slug])
  if (status === 'loading') return <><Header /><Loading /></>; if (status === 'error') return <><Header /><ErrorState message="That product doesn't exist or is currently unavailable." /></>; if (!product) return null
  const variant = product.variants[variantIndex]; const discount = Math.round((1 - variant.price / variant.mrp) * 100)
  return <><Header /><main className="detail"><button className="back-link" onClick={() => navigate('/products')}><ChevronLeft size={18} /> All devices</button><div className="detail-grid"><section className="visual"><div className="large-art"><ProductImage src={variant.imageUrl} alt={`${product.name} in ${variant.color}`} /></div><div className="trust-line"><ShieldCheck size={18} /><span>100% secure & transparent pricing</span></div></section><section className="details"><p className="eyebrow">{product.brand} / {variant.finish}</p><h1>{product.name}</h1><p className="description">{product.description}</p><div className="price-row"><strong>{money(variant.price)}</strong><span className="mrp">{money(variant.mrp)}</span><span className="discount">{discount}% off</span></div><p className="price-note">Price inclusive of all taxes</p><div className="rule" /><div className="selector-heading"><h2>Choose your variant</h2><span>{variant.color} / {variant.storage}</span></div><div className="variant-list">{product.variants.map((item, index) => <button className={`variant ${index === variantIndex ? 'active' : ''}`} key={item.id} onClick={() => { setVariantIndex(index); setSelectedPlan(null); setConfirmed(false) }}><ProductImage src={item.imageUrl} alt="" /><span><b>{item.color}</b><small>{item.storage}</small></span>{index === variantIndex && <Check size={16} />}</button>)}</div><div className="rule" /><div className="plans-heading"><div><h2>Select an EMI plan</h2><p>Choose a tenure that works for you</p></div><span className="fund-badge">Backed by mutual funds</span></div><div className="plans">{variant.emiPlans.map((plan) => <button className={`plan ${selectedPlan?.id === plan.id ? 'active' : ''}`} key={plan.id} onClick={() => { setSelectedPlan(plan); setConfirmed(false) }}><span className="plan-check">{selectedPlan?.id === plan.id && <Check size={13} />}</span><span className="plan-main"><strong>{money(plan.monthlyPayment)}<small>/ month</small></strong><span>{plan.tenureMonths} months</span></span><span className="plan-meta"><b>{plan.interestRate}% interest</b>{plan.cashback > 0 && <small>+ {money(plan.cashback)} cashback</small>}</span></button>)}</div><button className="button primary proceed" disabled={!selectedPlan} onClick={() => setShowConfirm(true)}>Proceed with selected plan <ArrowRight size={18} /></button>{!selectedPlan && <p className="select-hint">Select an EMI plan to continue</p>}{confirmed && <div className="success"><Check size={20} /><span>Your EMI plan has been selected successfully.</span></div>}</section></div></main>{showConfirm && <Confirmation product={product} variant={variant} plan={selectedPlan} onCancel={() => setShowConfirm(false)} onConfirm={() => { setShowConfirm(false); setConfirmed(true) }} />}</>
}
function Confirmation({ product, variant, plan, onCancel, onConfirm }) { return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={onCancel} aria-label="Close"><X size={19} /></button><p className="eyebrow">READY WHEN YOU ARE</p><h2>Confirm your selection</h2><p className="modal-copy">Review the details below before continuing.</p><div className="summary"><div><span>Product</span><b>{product.name}</b></div><div><span>Variant</span><b>{variant.color} / {variant.storage}</b></div><div><span>Price</span><b>{money(variant.price)}</b></div><div><span>Monthly EMI</span><b>{money(plan.monthlyPayment)} / month</b></div><div><span>Tenure</span><b>{plan.tenureMonths} months at {plan.interestRate}%</b></div><div><span>Cashback</span><b>{money(plan.cashback)}</b></div></div><div className="modal-actions"><button className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary" onClick={onConfirm}>Confirm plan <Check size={17} /></button></div></div></div> }
function Footer() { return <footer><Link className="logo" to="/products"><span className="logo-mark">1</span>fi<span className="logo-dot">.</span></Link><span>Thoughtful finance for thoughtful purchases.</span></footer> }
function App() { return <BrowserRouter><Routes><Route path="/" element={<Catalog />} /><Route path="/products" element={<Catalog />} /><Route path="/products/:slug" element={<Detail />} /><Route path="*" element={<Catalog />} /></Routes></BrowserRouter> }
export default App